#define INIT_TASK_PRIORITY           1
#define INIT_TASK_STACKSIZE       2048

#define HEARTBEAT_TASK_PRIORITY     0//42
#define HEARTBEAT_TASK_STACKSIZE  2048

#define SHELL_TASK_PRIORITY         20
#define SHELL_TASK_STACKSIZE      2048

#define ENCODER_TASK_PRIORITY        6
#define ENCODER_TASK_STACKSIZE    2048

#define CONTROL_TASK_PRIORITY        4
#define CONTROL_TASK_STACKSIZE    2048

#define PLOT_TASK_PRIORITY          21
#define PLOT_TASK_STACKSIZE       2048

#define DRIVE_TASK_PRIORITY         19
#define DRIVE_TASK_STACKSIZE      2048

