
#define HEARTBEAT_TASK_PRIORITY      5
#define HEARTBEAT_TASK_STACKSIZE  2048

#define SHELL_TASK_PRIORITY         40
#define SHELL_TASK_STACKSIZE      2048

#define ENCODER_TASK_PRIORITY        6
#define ENCODER_TASK_STACKSIZE    2048

#define CONTROL_TASK_PRIORITY        4
#define CONTROL_TASK_STACKSIZE    2048
